b2c_django/web/myadmin/urls.py
from django.conf.urls import url,include
from .views import userviews,typeviews,goodsviews,authviews

urlpatterns = [

	#后台首页
	url(r'^$',userviews.adminindex,name="admin_user_index"),
	# 后台登录页
	url(r'^login/$',authviews.mylogin,name="admin_login"),
	#退出登录
	url(r'^loginout/$',authviews.myloginout,name="admin_loginout"),
	#验证码
	url(r'^user/code/$',userviews.code,name="admin_user_code"),
    #首页信息
    url(r'^user/home/$',userviews.home,name="admin_home"),

   
    #管理员添加
    url(r'^auth/user/add/$',authviews.useradd,name="auth_useradd"),
    #管理员列表
    url(r'^auth/user/list/$',authviews.userlist,name="auth_userlist"),
    #管理员删除
    url(r'auth/user/del/(?P<uid>[0-9]+)$',authviews.userdel,name="auth_userdel"),
    #管理组添加
    url(r'^auth/group/add/$',authviews.groupadd,name="auth_groupadd"),
    #管理组列表
    url(r'^auth/group/list/$',authviews.grouplist,name="auth_grouplist"),
    #编辑组
    url(r'^auth/group/edit/(?P<gid>[0-9]+)$',authviews.groupedit,name="auth_groupedit"),



   	#用户
    url(r'^user/add/$',userviews.useradd,name="admin_user_add"),
    url(r'^user/insert/$',userviews.userinsert,name="admin_user_insert"),
    url(r'^user/list/$',userviews.userlist,name="admin_user_list"),
    url(r'^user/del/(?P<uid>[0-9]+)$',userviews.userdel,name="admin_user_del"),
    url(r'^user/edit/(?P<uid>[0-9]+)$',userviews.useredit,name="admin_user_edit"),
    url(r'^user/update/$',userviews.userupdate,name="admin_user_update"),
    url(r'^user/ajax/$',userviews.userajax,name="admin_user_ajax"),


    #类型
    url(r'^type/add$',typeviews.typeadd,name="admin_type_add"),
    url(r'^type/insert$',typeviews.typeinsert,name="admin_type_insert"),
    url(r'^type/list$',typeviews.typelist,name="admin_type_list"),
    url(r'^type/edit/(?P<tid>[0-9]+)$',typeviews.typeedit,name="admin_type_edit"),
    url(r'^type/update/$',typeviews.typeupdate,name="admin_type_update"),
    url(r'^type/del/$',typeviews.typedel,name="admin_type_del"),


    #商品
    url(r'^goods/add/$',goodsviews.goodsadd,name="admin_goods_add"),
    url(r'^goods/insert/$',goodsviews.goodsinsert,name="admin_goods_insert"),
    url(r'^goods/list/$',goodsviews.goodslist,name="admin_goods_list"),
    url(r'^goods/del/$',goodsviews.goodsdel,name="admin_goods_del"),
    url(r'^goods/edit/(?P<gid>[0-9]+)$',goodsviews.goodsedit,name="admin_goods_edit"),
    url(r'^goods/update/$',goodsviews.goodsupdate,name="admin_goods_update"),
    url(r'^goods/status/$',goodsviews.status,name="admin_goods_status"),


    #订单管理
    # url(r"^order/order/$",goodsviews.order,name="admin_order_order"),
    #订单发货
    url(r'^order/fagoods/(?P<oid>[0-9]+)$',goodsviews.fagoods,name="admin_order_fagoods"),
    #订单管理2
    url(r'^order/orders/',goodsviews.orders,name="admin_order_orders"),
    #订单查看
    url(r'^order/orderlook/(?P<aid>[0-9]+)$',goodsviews.orderlook,name="admin_order_orderlook"),
    #订单状态
    url(r'^order/statu/$',goodsviews.statu,name="admin_order_statu"),
]

b2c_django/web/web/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^ueditor/', include('ueditor.urls')),
    url(r'^admin/',include('myadmin.urls')),
    url(r'^',include('home.urls')),

]

b2c_django/web/myadmin/models.py
from django.db import models

# Create your models here.

#用户模型
class Users(models.Model):
	username=models.CharField(max_length=50)
	password=models.CharField(max_length=77)
	email=models.CharField(max_length=100,null=True)
	phone=models.CharField(max_length=20,null=True)
	sex=models.CharField(max_length=3,null=True)
	age=models.IntegerField(null=True)
	picurl=models.CharField(max_length=100,default="/static/pics/default/default.jpg")
	status=models.IntegerField(default=0)#0正常 1禁用
	addtime=models.DateTimeField(auto_now_add=True)
	def __str__(self):

		return self.username

	class Meta:
		permissions = (
			("show_users", "查看会员管理"),
			("insert_users", "添加会员管理"),
			("edit_users", "修改会员管理"),
			("del_users", "删除会员管理"),
		)

#分类模型
class Types(models.Model):
	name=models.CharField(max_length=50)
	pid=models.IntegerField()
	path=models.CharField(max_length=50)
	def __str__(self):

		return self.name
	class Meta:
		permissions = (
			("show_types", "查看商品分类管理"),
			("insert_types", "添加商品分类管理"),
			("edit_types", "修改商品分类管理"),
			("del_types", "删除商品分类管理"),
		)



#商品模型
class Goods(models.Model):
	typeid=models.ForeignKey(to="Types",to_field="id")
	title=models.CharField(max_length=255)
	price=models.DecimalField(max_digits=8,decimal_places=2)
	storage=models.IntegerField()
	pic=models.CharField(max_length=50)
	info=models.TextField()
	num=models.IntegerField(default=0)
	clicknum=models.IntegerField(default=0)
	status=models.IntegerField(default=1)#1:新品2：热销3：下架
	addtime=models.DateTimeField(auto_now_add=True)
	def __str__(self):

		return self.title
	class Meta:
		permissions = (
			("show_goods", "查看商品管理"),
			("insert_goods", "添加商品管理"),
			("edit_goods", "修改商品管理"),
			("del_goods", "删除商品管理"),
		)

#地址模型
class Address(models.Model):
	#用户id
	uid=models.ForeignKey(to='Users',to_field="id")
	aname=models.CharField(max_length=20)
	adds=models.CharField(max_length=255)
	aphone=models.CharField(max_length=11)
	#是否为默认1 默认
	status=models.IntegerField(default=0)

	class Meta:
		permissions = (
			("show_address", "查看地址管理"),
			("insert_address", "添加地址管理"),
			("edit_address", "修改地址管理"),
			("del_address", "删除地址管理"),
		)


# 订单表
class Order(models.Model):

	uid =models.ForeignKey("Users",to_field="id")
	address = models.ForeignKey('Address',to_field='id')
	totalprice = models.FloatField()
	totalnum = models.IntegerField()
	# 1 未付款 2已付款,待发货,3已发货,待收货,4已完成,5已取消
	status = models.IntegerField()
	addtime = models.DateTimeField(auto_now_add=True)
	wuliu=models.CharField(max_length=255, null=True)
	oddnum=models.CharField(max_length=255,null=True)


	class Meta:
		permissions = (
			("show_order", "查看订单管理"),
			("insert_order", "添加订单管理"),
			("edit_order", "修改订单管理"),
			("del_order", "删除订单管理"),
		)





# 订单详情
class OrderInfo(models.Model):
	orderid = models.ForeignKey('Order',to_field="id")
	gid =  models.ForeignKey('Goods',to_field="id")
	num = models.IntegerField()
	price = models.FloatField()



	

b2c_django/web/myadmin/views/authviews.py
from django.shortcuts import render
from django.http import HttpResponse,JsonResponse
from ..  models import *
from django.urls import reverse
from django.contrib.auth.models import User,Permission,Group
from django.contrib.auth import authenticate,login,logout 












#管理员添加
def useradd(request):

	#判断是请求页面或提交
	if request.method == "GET":

		#查询所有组
		per=Group.objects.all()
		info={"per":per}
		return render(request,"myadmin/auth/add.html",info)
	elif request.method == "POST":
		s=request.POST.get("super","")
		
		
		if s:
			ob=User.objects.create_superuser(request.POST["username"],request.POST["email"],request.POST["password"])
		
		else:
			ob=User.objects.create_user(request.POST["username"],request.POST["email"],request.POST["password"])	

		ob.save()
		# 判断是否有选权限组
		prms=request.POST.getlist("prms",None)
		if prms:
			ob.groups.set(prms)
			ob.save()

		return HttpResponse("<script>alert('成功');location.href='"+reverse("auth_userlist")+"'</script>")




#管理元列表
def userlist(request):

	ob=User.objects.all()

	return render(request,'myadmin/auth/list.html',{"ob":ob})


# 管理员删除
def userdel(request,uid):

    ob = User.objects.get(id=uid)
    ob.delete()
    return HttpResponse('<script>location.href="/admin/auth/user/list"</script>')

#添加组
def groupadd(request):
	if request.method == "GET":
		per=Permission.objects.exclude(name__istartswith="Can")
		return render(request,"myadmin/group/add.html",{"per":per})

	elif request.method == "POST":
		# 获取选择的所有权限
		l=request.POST.getlist("prms",None)

		# 创建组
		g = Group(name=request.POST['username'])
		g.save()

	
	
		# 判断是否需要给组添加权限
		if l:
			# 给组分配权限
			g.permissions.set(l)
			g.save()


			return HttpResponse("<script>alert('成功');location.href='"+reverse("auth_grouplist")+"'</script>")


#组列表
def grouplist(request):
	g=Group.objects.all()


	return render(request,"myadmin/group/list.html",{"ob":g})

#组编辑
def groupedit(request,gid):
	# 查询组
	ginfo=Group.objects.get(id=gid)

	if request.method =="GET":	
		per=Permission.objects.exclude(group=ginfo).exclude(name__istartswith="Can")

		info={"ginfo":ginfo,"per":per}
		
		return render(request,"myadmin/group/edit.html",info)
	

	elif request.method == "POST":

		#接受发来的参数
		prms=request.POST.getlist("prms",None)
		print(prms)
		#修改组名
		ginfo.name=request.POST["name"]
		#清空当前组的权限
		ginfo.permissions.clear()
		if prms:
			ginfo.permissions.set(prms)

		ginfo.save()

		return HttpResponse("<script>alert('成功');location.href='"+reverse("auth_grouplist")+"'</script>")

#登录页
def mylogin(request):
	if request.method=="GET":

		return render(request,'myadmin/login.html')
	elif  request.method=="POST":

		#检测验证码是否正确
		if request.POST["code"].lower() != request.session["verifycode"].lower():
			return HttpResponse("<script>alert('验证码不正确');location.href='/admin/login'</script>")

		#使用django 提公的后台验证方法
		username=request.POST["username"]
		password=request.POST["password"]
		user = authenticate(request,username=username,password=password)
	
		if user:
			login(request,user)
	
			return render(request,'myadmin/index.html')
		return HttpResponse("<script>alert('用户名不存在或密码不正确');location.href='/admin/login'</script>")

	# 	ob=Users.objects.filter(username=request.POST["username"])
	# 	# 真则表示有这条数据
	# 		#判断密码是否正确
	# 		if check_password(request.POST['password'],ob[0].password):
			
	# 			#密码正确 判断是否是管理员权限
	# 			if ob[0].status==2:
	# 				request.session["AdminUser"]={"username":ob[0].username,"pic":ob[0].picurl}
	# 				request.session.set_expiry(0)
	# 			else:
	# 				return HttpResponse("<script>alert('您没有权限登录');location.href='/admin/login'</script>")
			
			
#退出登录	
def myloginout(request):
	# del request.session['AdminUser']
	logout(request)
	return HttpResponse("<script>alert('退出成功');location.href='/admin/login'</script>")

b2c_django/web/myadmin/views/goodsviews.py
from django.shortcuts import render
from django.http import HttpResponse,JsonResponse
from ..  models import *
from django.urls import reverse
from django.db.models import Q
from django.contrib.auth.decorators import permission_required




@permission_required("myadmin.insert_goods",raise_exception = True)
def goodsadd(request):

	from . typeviews import order

	info={"tlist":order(request)}

	return render(request,'myadmin/goods/add.html',info)

@permission_required("myadmin.insert_goods",raise_exception = True)
def goodsinsert(request):
	if not request.FILES.get("pic",None):
		return HttpResponse("<script>alert('请选择上传图片');location.href='"+reverse("admin_goods_add")+"'</script>") 

	ob=Goods()
	ob.typeid=Types.objects.get(id=request.POST["typeid"])
	ob.title=request.POST["title"]
	ob.price=request.POST["price"]
	ob.storage=request.POST["storage"]
	ob.pic=upload(request)
	ob.info=request.POST["info"]
	ob.save()
	return HttpResponse('<script>alert("添加成功");location.href="/admin/goods/list/"</script>')


@permission_required("myadmin.show_goods",raise_exception = True)
def goodslist(request):
	#获取是否排序

	#接收所搜索参数
	keywords=request.GET.get("keywords",None)
	j=request.GET.get("j",None)
	# 接收区间搜索值
	begin=request.GET.get("begin","")
	end=request.GET.get("end","")

	
	# 判断是否有搜索条件
	if  keywords and j :
		ob= Goods.objects.filter(title__contains=keywords).order_by("price")
	
	elif keywords:
		ob=Goods.objects.filter(title__contains=keywords)


	elif j :
		ob=Goods.objects.order_by("price")
	
	elif begin and end=="":
		ob=Goods.objects.filter(price__gte=begin)
	elif end and begin=="":
		ob=Goods.objects.filter(price__lte=end)
	elif end and begin:
		ob=Goods.objects.filter(Q(price__gte=begin),Q(price__lte=end))
	
	else:
		ob=Goods.objects.all()


	#分页
	from django.core.paginator import Paginator
	# 实例化分页类
	paginator = Paginator(ob,5)
	
	# 获取当前页码
	p=int(request.GET.get('p',1))

	# 获取分页数据对象
	goodslist= paginator.page(p)
	
	
	info={"ob":goodslist}





	return render(request,"myadmin/goods/list.html",info)


@permission_required("myadmin.edit_goods",raise_exception = True)
def goodsedit(request,gid):
	ob=Goods.objects.get(id=gid)
	from . typeviews import order

	info={"ob":ob,"glist":order(request)}
	return render(request,"myadmin/goods/edit.html",info)


@permission_required("myadmin.del_goods",raise_exception = True)
def goodsdel(request):
	ob=Goods.objects.get(id=request.GET["gid"])
	import os
	os.remove('.'+ob.pic)


	ob.delete()

	return JsonResponse({"msg":"OK"})

@permission_required("myadmin.edit_goods",raise_exception = True)
def goodsupdate(request):

	ob=Goods.objects.get(id=request.POST.get("gid"))
	try:
		ob.typeid=Types.objects.get(id=request.POST["typeid"])
		ob.price=request.POST["price"]
		ob.title=request.POST["title"]
		ob.storage=request.POST["storage"]
		ob.info=request.POST["info"]
		ob.title=request.POST["title"]
		# print(request.FILES['pic'])
		# 判断是否有文件上传
		if request.FILES.get("pic",None):
		 	# 判断是否使用的默认图
			if ob.pic != '/static/pics/default/default.jpg':
				import os
				os.remove('.'+ob.pic)

			ob.pic =  upload(request)
	    # 执行更新
		ob.save()
		res="<script>alert('修改成功');location.href='"+reverse("admin_goods_list")+"'</script>"
	except:
		res="<script>alert('修改成功');location.href='admin/goods/edit/"+ob.id+"'</script>"

	return HttpResponse(res)

#状态
def status(request):
	ob=Goods.objects.get(id=request.GET["uid"])
	ob.status=int(request.GET["val"])
	ob.save()
	return HttpResponse("")

#上传图片
def upload(request):

	if not request.FILES.get("pic"):
		return '/static/pics/default/default.jpg'
 	

	import random,time
	#定义文件随机数
	
	time='{time}{sui}.'.format(sui=random.randrange(1000,9999),time=int(time.time()))

	#取后缀名
	res=(str(request.FILES.get("pic")).split(".")).pop()


	path="/static/pics/goods/"+time+res

	if res.upper() not in ["BMP","JPG","JPEG","PNG","GIF"]:
		return False
	#打开文件
	fs=open('.'+path,"wb+")
	#分片写入
	for i  in  request.FILES.get("pic").chunks():
		fs.write(i)
	#关闭文件
	fs.close()

	return path


#订单发货
def fagoods(request,oid):
	
	if request.method=="GET":
		return render(request,'myadmin/goods/fagoods.html')
	elif request.method=="POST":

		
	
		# 查找发货的订单
		order=Order.objects.get(id=oid)
		order.status=3
		# 提交表单
		order.wuliu=request.POST.get("wuliu")
		order.oddnum=request.POST.get("oddnum")
		order.save()
		return HttpResponse("<script>alert('发货成功');location.href='"+reverse("admin_order_orders")+"'</script>")

#订单管理2
def orders(request):
	# 接收所搜索参数
	statu=request.GET.get("type","0")
	if statu=="0":
		#查询所有订单
		orderss=Order.objects.all()
	elif statu=="1":
		#查询未付款的订单
		orderss=Order.objects.filter(status=1)
	elif statu=="2":
		#查询代发货的订单
		orderss=Order.objects.filter(status=2)
	elif statu=="3":
		#查询已发货的订单
		orderss=Order.objects.filter(status=3)



	#分页
	from django.core.paginator import Paginator
	# 实例化分页类
	paginator = Paginator(orderss,5)
	
	# 获取当前页码
	p=int(request.GET.get('p',1))

	# 获取分页数据对象
	orderlist= paginator.page(p)
	
	#分配数据	
	info={"ob":orderlist}


	return render(request,'myadmin/goods/order.html',info)



#订单查看
def orderlook(request,aid):
	#接收订单号
	ob=Order.objects.filter(id=aid)
	info={"order":ob}

	return render(request,'myadmin/goods/orderlook.html',info)


# #订单状态修改
def statu(request):
	status=request.GET["v"]
	print(status)
	ids=int(request.GET["i"])
	#查找订单
	ob=Order.objects.get(id=ids)
	ob.status=status
	ob.save()
	return HttpResponse("ok")

b2c_django/web/templates/myadmin/goods/add.html
{%extends 'myadmin/public/base.html' %}

{% block con-header %}
<div class="container-fluid am-cf">
    <div class="row">
        <div class="am-u-sm-12 am-u-md-12 am-u-lg-9">
            <div class="page-header-heading"><span class="am-icon-home page-header-heading-icon"></span>会员添加</div>
           
        </div>
        <div class="am-u-lg-3 tpl-index-settings-button">
            <button type="button" class="page-header-button"><span class="am-icon-paint-brush"></span> 设置</button>
        </div>
    </div>

</div>
{%endblock%}
{%block con-body%}
<div class="row am-cf">

<div class="widget am-cf">


        <div class="widget-body am-fr">

            <form class="am-form tpl-form-line-form" action="{% url 'admin_goods_insert' %}" method="post" enctype="multipart/form-data" >

             <div class="am-form-group">
                            <label for="user-name" class="am-u-sm-3 am-form-label">
                                所属分类
                            </label>
                            <select name="typeid" data-am-selected="{btnSize: 'sm'}" style="display: none;">
                              {% for v in tlist %}
                                  {% if v.pid == 0 %}
                                    <option disabled value="{{ v.id }}">{{ v.name }}</option>
                                  {% else %}
                                    <option value="{{ v.id }}">{{ v.name }}</option>
                                  {% endif %}
                              {% endfor %}
                            </select>
                </div>




                <div class="am-form-group">
                    <label for="user-name" class="am-u-sm-3 am-form-label" >商品介绍</label>
                    
                    <div class="am-u-sm-9">
                        <input class="tpl-form-input username" id="user-name" placeholder="title" type="text"  name="title">
                        
                    </div>
                </div>

               <div class="am-form-group">
                    <label for="user-name" class="am-u-sm-3 am-form-label" >价格</label>
                    
                    <div class="am-u-sm-9">
                        <input class="tpl-form-input username" id="user-name" placeholder="price" type="text"  name="price">
                        
                    </div>
                </div>
                
                <div class="am-form-group">
                    <label for="user-name" class="am-u-sm-3 am-form-label" >库存</label>
                    
                    <div class="am-u-sm-9">
                        <input class="tpl-form-input username" id="user-name" placeholder="storage" type="text"  name="storage">
                        
                    </div>
                </div>
                



                <div class="am-form-group">
                    <label for="user-weibo" class="am-u-sm-3 am-form-label">商品图片 </label>
                    <div class="am-u-sm-9">
                        <div class="am-form-group am-form-file">
                            <div class="tpl-form-file-img">
                                <img src="/static/pics/default/default.jpg" class="imgg" alt="" style="width: 100px">
                            </div>
                            <button type="button" class="am-btn am-btn-danger am-btn-sm">
                        <i class="am-icon-cloud-upload" ></i> 添加商品图片</button>
                            <input id="doc-form-file" multiple="" type="file" name="pic" >
                        </div>

                    </div>
                </div>

                 <div class="am-form-group">
                            <label for="user-name" class="am-u-sm-3 am-form-label">
                                商品详情
                            </label>
                            <div class="am-u-sm-9">
                                <link rel="stylesheet" type="text/css" href="/ueditor/UE/third-party/SyntaxHighlighter/shCoreDefault.css">
                                <script type="text/javascript" src="/ueditor/UE/third-party/SyntaxHighlighter/shCore.js"></script>
                                <script type="text/javascript" src="/ueditor/UE/ueditor.config.js"></script>
                                <script type="text/javascript" src="/ueditor/UE/ueditor.all.min.js"></script>
                                <script type="text/javascript" src="/ueditor/UE/lang/zh-cn/zh-cn.js"></script>

                                <script id="editor" name="info" type="text/plain" style="height:300px; width:350px;color:#000;">
                                    请输入商品详情内容
                                </script>
                                
                                <script type="text/javascript">
                                   var ue = UE.getEditor('editor');
                                   SyntaxHighlighter.all();
                                </script>
                            </div>
                 </div>



                <div class="am-form-group">
                    <div class="am-u-sm-9 am-u-sm-push-3">
                        <button type="sublit" id="but" class="am-btn am-btn-primary tpl-btn-bg-color-success ">提交</button>
                    </div>
                </div>
                {% csrf_token %}
           </form>
        </div>
</div>
                
</div>

<script type="text/javascript">
    $('#doc-form-file').change(function(){
        var a = $('.imgg').attr('src',URL.createObjectURL($(this)[0].files[0]));
       
    })

    // $(".username").blur(function(){
    //  var a=$(".username").val()

        
    // })

 
    
    

</script>
{%endblock%}

b2c_django/web/templates/myadmin/goods/orderlook.html
{%extends 'myadmin/public/base.html' %}
{% block con-header %}
<div class="container-fluid am-cf">
    <div class="row">
        <div class="am-u-sm-12 am-u-md-12 am-u-lg-9">
            <div class="page-header-heading"><span class="am-icon-home page-header-heading-icon"></span>订单详情</div>
           
        </div>
        <div class="am-u-lg-3 tpl-index-settings-button">
            <button type="button" class="page-header-button"><span class="am-icon-paint-brush"></span> 设置</button>
        </div>
    </div>

</div>
{%endblock%}



{% block con-body %}
<div class="row-content am-cf">
    <div class="row">
        <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">
            <div class="widget am-cf">
               
                <div class="widget-body  am-fr">

                    <div class="am-u-sm-12 am-u-md-6 am-u-lg-6">
                        <div class="am-form-group">
                            <div class="am-btn-toolbar">
                               
                            </div>
                        </div>
                    </div>
                    <!-- 条件搜索 -->
                   
                    <!-- 展示内容 -->
                <div class="am-u-sm-12">
                    <table width="100%" class="am-table am-table-compact am-table-striped tpl-table-black ">

                    <tbody>
                        {% for i in order %}    
                        <tr class="trHead hidden-xs hidden-sm">
                            <td colspan="4" class="title clearfix">
                              <div class="f-fl">下单时间：<span class="time">{{ i.addtime|date:"Y-m-d H-i-s"  }}</span>订单号：<span class="orderNumber">{{ i.id }}</span>
                              </div>
                            </td>
                        </tr>
                        
                        <tr class="list-box b-l b-r b-b">
                            <td class="list b-r j-iamCart">
                                <div class="cart-wrap j-CartWrap">
                                    <div class="shop j-shop j-amLight">
                                    {%  for ii in i.orderinfo_set.all %}
                                
                                
                                    
                                    <div class="item b-t clearfix j-item j-iamMain">
                                        <a class="productDetail nameWidth col-xs-4 col-sm-4" href="//detail.meizu.com/item/pro7.html" target="_blank">
                                            <img src="{{ ii.gid.pic  }}" style="width:100px;height: 100px" class="f-fl">
                                        </a>
                                        <div class="describe f-fl col-xs-8 col-sm-8">
                                            <div class="vertic clearfix">
                                                <span class="clearfix">
                                                    <a class="productDetail nameWidth" href="#" target="_blank">
                                                        <i>{{ ii.gid.title }}</i> <i class="pro-d"></i>
                                                    </a>
                                                    <p>
                                                    ￥{{ ii.gid.price }} × {{ ii.num }}
                                                    </p>
                                                </span>
                                            </div>
                                        </div>
                                        <input class="orderSn" value="51090244361541573081" type="hidden">
                                        <input class="isCart" value="1" type="hidden">
                                        <input class="orderSnSon" value="21090244361541579081" type="hidden">
                                    </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </td>

                            <td class="b-r w125 center price b-t hidden-xs hidden-sm">
                                <div class="priceDiv">
                                    总价: <br><br>{{ i.totalprice }}元
                                    
                                </div>
                            </td>
                            <td class="b-r w125 center state b-t hidden-xs hidden-sm">
                                <div class="stateDiv">
                                {% if i.status == 1  %}

                                    <div>订单状态:<br>待付款<br></div>

                                {% elif i.status == 2  %}
                                    <div>订单状态:<br>已付款,待发货<br></div>
                                
                                {% elif i.status == 3  %}
                                    <div>订单状态:<br>已发货,待收货<br> <br> </div>
                                    <div>{{ i.wuliu  }}:<br>{{ i.oddnum }}</div><br>

                                {% elif i.status == 4  %}
                                    <div>订单状态:<br>已完成<br></div><br>

                                {% elif i.status == 4  %}
                                    <div>订单状态:<br>已取消<br></div> <br>     

                                {% endif %}
                                </div>
                            </td>
                            <td class="w125 center opreat b-t hidden-xs hidden-sm">
                                <ul>
                                	下单用户:<br> {{ i.uid.username }}<br> <br> 
                                   下单地址:<br> {{ i.address.adds  }}<br> <br> 
                                   联系电话:<br>{{ i.address.aphone }}<br> <br> 
                                </ul>
                            </td>

                        </tr>
                        
                    {% endfor %}    
                    </tbody>
                       
            </table>
        </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(".user_status_save").click(function(){
        val=$(this).val()
        uid=$(this).attr("uid")
        $.get('{%url "admin_user_ajax"%}', {uid:uid,val:val})

    })


</script>
{% endblock %}