books/mydjango-master/bookms2/app01/urls.py
# -*- coding: utf-8 -*-

from django.contrib import admin
from django.urls import path, re_path, include
from app01 import views

app_name = 'app01'
urlpatterns = [
    re_path(r'^addbook/', views.add_book, name='addbook'),
    re_path(r'^books/', views.books, name='books'),
    re_path(r'^app01/books/(\d+)/delete',views.del_book,name='delete'),
    re_path(r'^app01/books/(\d+)/modify',views.mod_book,name='modify'),
    re_path(r'^app01/books/(\d+)/(\d+)/aut_detail/',views.aut_detail,name='aut_detail'),
]

books/mydjango-master/bookms2/bookms2/urls.py
from django.contrib import admin
from django.urls import path,re_path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^app01/',include('app01.urls',namespace='app01'))
]

books/mydjango-master/bookms2/app01/models.py
from django.db import models


# Create your models here.

class Author(models.Model):
    """
    作者表的创建
    """
    nid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=32)
    age = models.IntegerField()
    # 与AuthorDetail创建一对一的关系
    author_detail = models.OneToOneField(to="AuthorDetail", on_delete=models.CASCADE)


class AuthorDetail(models.Model):
    nid = models.AutoField(primary_key=True)
    birthday = models.DateField()
    telephone = models.BigIntegerField()
    address = models.CharField(max_length=64)


class Publish(models.Model):
    nid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=32)
    city = models.CharField(max_length=64)
    email = models.EmailField()


class Book(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=32)
    pub_date = models.DateField()
    price = models.DecimalField(max_digits=5, decimal_places=2)
    # 与Publish建立一对多的关系，外键字段建立在多的一方
    publish = models.ForeignKey(to="Publish",to_field='nid',on_delete=models.CASCADE)
    # 与Author表建立多对多的关系，ManyToManyField可以建在两个模型中的任意一个，自动创建第三张表
    authors = models.ManyToManyField(to='Author',)

books/mydjango-master/bookms2/app01/views.py
from django.shortcuts import render, redirect, HttpResponse
from app01.models import *


# Create your views here.
def add_book(request):
    """
    添加书籍信息的视图函数
    :param request:
    :return:
    """
    if request.POST:
        title = request.POST.get("title")
        price = request.POST.get("price")
        date = request.POST.get("date")
        publish = request.POST.get("publish")
        authors = request.POST.getlist('authors')
        book_obj = Book.objects.create(title=title, price=price, pub_date=date, publish_id=publish)
        book_obj.authors.add(*authors)
        return redirect('app01:books')

    pub_list = Publish.objects.all()
    aut_list = Author.objects.all()

    return render(request, 'add_book.html', {'pub_list': pub_list, 'aut_list': aut_list})


def mod_book(request, id):
    mod_obj = Book.objects.filter(nid=id).first()
    if request.POST:
        title = request.POST.get("title")
        price = request.POST.get("price")
        date = request.POST.get("date")
        publish = request.POST.get("publish")
        authors = request.POST.getlist('authors')
        Book.objects.filter(pk=id).update(title=title, price=price, pub_date=date, publish_id=publish)
        mod_obj.authors.set(authors)
        return redirect('app01:books')

    pub_list = Publish.objects.all()
    aut_list = Author.objects.all()
    return render(request, 'modbook.html', {'mod_obj': mod_obj, 'pub_list': pub_list, 'aut_list': aut_list})


def books(request):
    book_list = Book.objects.all()

    return render(request, 'books.html', {'book_list': book_list})


def del_book(request, id):
    Book.objects.filter(nid=id).delete()
    return redirect('app01:books')


def aut_detail(request, id, tag):
    if tag == "2":
        print(id)
        book_list = Book.objects.filter(authors__nid=id).all()
    else:
        book_list = Book.objects.filter(publish_id=id).all()
    return render(request, 'book_detail.html', locals())

books/mydjango-master/bookms2/templates/add_book.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
     <div class="row">
         <div class="col-md-6 col-md-offset-3">
             <form action="" method="post">
                 {% csrf_token %}
                 <div class="form-group">
                     <label for="">书籍名称</label>
                     <input type="text" class="form-control" name="title">
                 </div>
                 <div class="form-group">
                     <label for="">价格</label>
                     <input type="text" class="form-control" name="price">
                 </div>
                 <div class="form-group">
                     <label for="">出版日期</label>
                     <input type="date" class="form-control" name="date">
                 </div>
                 <div class="form-group">
                     <label for="">出版社</label>
                     <select class="form-control" name="publish">
                          {% for pub in pub_list%}
                              <option value="{{ pub.pk }}">
                              {{ pub.name }}
                              </option>
                          {% endfor %}
                     </select>

                 </div>
             <div class="form-group">
                     <label for="">作者</label>
                     <select class="form-control" name="authors" type="text" multiple >
                          {% for aut in aut_list%}
                              <option value="{{ aut.pk }}">
                              {{ aut.name}}
                              </option>
                          {% endfor %}
                     </select>

                 </div>

                 <input type="submit" class="btn btn-success pull-right">


             </form>
         </div>
     </div>
</div>
{% endblock %}

books/mydjango-master/bookms2/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/bs/css/bootstrap.css">
    <style>
        .container {
            margin-top: 100px;
        }

        .btn {
            margin-top: 10px;
        }

        * {
            margin: 0;
            padding: 0;
        }

        #content {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            min-width: 1000px;
            z-index: -10;
            zoom: 1;
            background-color: #fff;
            background-repeat: no-repeat;
            background-size: cover;
            -webkit-background-size: cover;
            -o-background-size: cover;
            background-position: center 0;
            background-image: url("https://images.pexels.com/photos/1340588/pexels-photo-1340588.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260");
        }

        .mytable {
            background-color: #999999;
        }

        .mynav {
            background-color: #222222;
        }
    </style>
</head>
<body>


<div id="content">
    <ul class="nav nav-tabs mynav">
        <li role="presentation"><a href="{% url 'app01:books' %}">Home</a></li>
        <li role="presentation"><a href="{% url 'app01:addbook' %}">AddBook</a></li>
    </ul>
    {% block content %}{% endblock %}
</div>
<script src="/static/jq/jquery-3.3.1.js"></script>

</body>
</html>

books/mydjango-master/bookms2/templates/book_detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="page-header">
        <h1>LuffyCity
            <small>BookManage</small>
        </h1>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <a href="{% url 'app01:addbook' %}" class="btn btn-primary">添加书籍</a>
                <table class="table table-striped table-bordered mytable">
                    <thead>
                    <tr>
                        <th>书籍名称</th>
                        <th>价格</th>
                        <th>出版日期</th>
                        <th>出版社</th>
                        <th>作者</th>
                        <th>删除操作</th>
                        <th>编辑操作</th>
                    </tr>
                    </thead>
                    <tbody>

                    {% for my_book in book_list %}
                        <tr>
                            <td>{{ my_book.title }}</td>
                            <td>{{ my_book.price }}</td>
                            <td>{{ my_book.pub_date|date:'Y-m-d' }}</td>
                            <td>{{my_book.publish.name }}</td>
                            <td>
                                {% for aut in my_book.authors.all %}
                                    {% if forloop.last %}
                                        <span>{{ aut.name }}</span>
                                    {% else %}
                                        <span>{{ aut.name }},</span>
                                    {% endif %}
                                {% endfor %}
                            </td>
                            <td><a href="{% url 'app01:delete' my_book.nid %}" class="btn btn-danger">删除</a></td>
                            <td><a href="{% url 'app01:modify' my_book.nid %}" class="btn btn-info">编辑</a></td>
                        </tr>

                    {% endfor %}

                    </tbody>

                </table>
            <a href="{% url 'app01:books' %}" class="btn btn-success center-block">返回</a>

            </div>
        </div>
    </div>
{% endblock %}

books/mydjango-master/bookms2/templates/books.html
{% extends 'base.html' %}
{% block content %}
    <div class="page-header center-block">
        <h1 style="color: aliceblue" class="text-center">LuffyCity
            <small>BookManage</small>
        </h1>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <table class="table table-striped table-bordered mytable">
                    <thead>
                    <tr style="background-color: rgba(0,0,0,0.6);color: white">
                        <th>书籍名称</th>
                        <th>价格</th>
                        <th>出版日期</th>
                        <th>出版社</th>
                        <th>作者</th>
                        <th>删除操作</th>
                        <th>编辑操作</th>
                    </tr>
                    </thead>
                    <tbody>

                    {% for my_book in book_list %}
                        <tr>
                            <td>{{ my_book.title }}</td>
                            <td>{{ my_book.price }}</td>
                            <td>{{ my_book.pub_date|date:'Y-m-d' }}</td>
                            <td>
                                <a href="{% url 'app01:aut_detail' my_book.publish.nid  1%}">{{ my_book.publish.name }}</a>
                            </td>
                            <td>
                                {% for aut in my_book.authors.all %}

                                    {% if forloop.last %}

                                        <a href="{% url 'app01:aut_detail' aut.pk  2%}">{{ aut.name }}</a>
                                    {% else %}
                                        <a href="{% url 'app01:aut_detail' aut.pk  2%}">{{ aut.name }},</a>

                                    {% endif %}
                                {% endfor %}
                            </td>
                            <td><a href="{% url 'app01:delete' my_book.nid %}" class="btn btn-danger">删除</a></td>
                            <td><a href="{% url 'app01:modify' my_book.nid %}" class="btn btn-info">编辑</a></td>
                        </tr>

                    {% endfor %}

                    </tbody>

                </table>
                            <a href="{% url 'app01:addbook' %}" class="btn btn-primary center-block">添加书籍</a>



            </div>
        </div>
    </div>
{% endblock %}

books/mydjango-master/bookms2/templates/modbook.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="">书籍名称</label>
                        <input type="text" class="form-control" name="title" value="{{ mod_obj.title }}">
                    </div>
                    <div class="form-group">
                        <label for="">价格</label>
                        <input type="text" class="form-control" name="price" value="{{ mod_obj.price }}">
                    </div>
                    <div class="form-group">
                        <label for="">出版日期</label>
                        <input type="date" class="form-control" name="date" value="{{ mod_obj.pub_date|date:'Y-m-d' }}">
                    </div>
                    <div class="form-group">
                        <label for="">出版社</label>
                        <select class="form-control" name="publish">
                            {% for pub in pub_list %}
                                {% if pub == mod_obj.publish %}
                                    <option value="{{ pub.pk }}" selected>
                                        {{ pub.name }}
                                    </option>
                                {% else %}
                                    <option value="{{ pub.pk }}">
                                        {{ pub.name }}
                                    </option>


                                {% endif %}





                            {% endfor %}
                        </select>

                    </div>
                    <div class="form-group">
                        <label for="">作者</label>
                        <select class="form-control" name="authors" type="text" multiple>
                            {% for aut in aut_list %}
                                {% if aut in mod_obj.authors.all %}
                                    <option value="{{ aut.pk }}" selected>
                                        {{ aut.name }}
                                    </option>
                                {% else %}
                                    <option value="{{ aut.pk }}">
                                        {{ aut.name }}
                                    </option>


                                {% endif %}

                            {% endfor %}
                        </select>

                    </div>

                    <input type="submit" class="btn btn-success pull-right">


                </form>
            </div>
        </div>
    </div>
{% endblock %}